root = "."
tmp_dir = "tmp"

[build]
  cmd = "dlv debug ./cmd --headless --listen=:2345 --api-version=2 --accept-multiclient --log"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  include_ext = ["go"]
  kill_delay = "1s"
  rerun = false
  send_interrupt = true

[log]
  time = true

[screen]
  clear_on_rebuild = false
