common:
  env: local
  gracefulTimeout: 2s
  storefront:
    http:
      protocol: http
      host: localhost
      port: "8080"
      idleTimeout: 10s
      readTimeout: 10s
      writeTimeout: 10s
    kafka:
      addr: kafka:9092
      producerTopic: storefront.events
      groupTopics:
        - payment.events 
      groupID: storefront-service-group
  inventory:
    http:
      protocol: http
      host: localhost
      port: "8081"
      idleTimeout: 10s
      readTimeout: 10s
      writeTimeout: 10s
    db:
      host: inventory-db
      port: "5432"
      user: inventory
      password: inventory
      name: inventory
    kafka:
      addr: kafka:9092
      producerTopic: inventory.events 
      groupTopics:
        - order.events
        - payment.events
      groupID: inventory-service-group
  payment:
    http:
      protocol: http
      host: localhost
      port: "8083"
      idleTimeout: 10s
      readTimeout: 10s
      writeTimeout: 10s
    kafka:
      addr: kafka:9092
      producerTopic: payment.events
      groupTopics:
        - inventory.events 
        - order.events
      groupID: payment-service-group
  order:
    http:
      protocol: http
      host: localhost
      port: "8082"
      idleTimeout: 10s
      readTimeout: 10s
      writeTimeout: 10s
    db:
      host: order-db
      port: "5432"
      user: order
      password: order
      name: order
    kafka:
      addr: kafka:9092
      producerTopic: order.events
      groupTopics:
        - inventory.events 
        - payment.events
      groupID: order-service-group

dev:
  env: dev

prod:
  env: prod
  storefront:
    http:
      host: storefront-service
  order:
    http:
      host: order-service
  payment:
    http:
      host: payment-service
  inventory:
    http:
      host: inventory-service