# Order Service Configuration

# Database Configuration
database:
  host: "localhost"
  port: 5432
  user: "order"
  password: "orderpass"
  name: "order"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

# Kafka Configuration
kafka:
  broker: "localhost:9092"
  topic: "order-events"
  group_id: "order-service"
  auto_offset_reset: "earliest"

# Server Configuration
server:
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

# Logging Configuration
logging:
  level: "info"
  format: "json"

# Order Configuration
order:
  default_status: "pending"
  allowed_statuses:
    - "pending"
    - "confirmed"
    - "cancelled"
    - "shipped"
    - "delivered"
    - "returned" 